-- MySQL Script generated by MySQL Workbench
-- Fri Dec  8 13:23:05 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbsystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbsystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbsystem` DEFAULT CHARACTER SET utf8 ;
USE `dbsystem` ;

-- -----------------------------------------------------
-- Table `dbsystem`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsystem`.`category` (
  `idcategory` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(256) NULL,
  `state` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idcategory`),
  UNIQUE INDEX `nombre_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsystem`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsystem`.`article` (
  `idarticle` INT NOT NULL AUTO_INCREMENT,
  `idcategory` INT NOT NULL,
  `code` VARCHAR(50) NULL,
  `name` VARCHAR(100) NOT NULL,
  `stock` INT NOT NULL,
  `description` VARCHAR(256) NULL,
  `image` VARCHAR(50) NULL,
  `state` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idarticle`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_article_category_idx` (`idcategory` ASC),
  CONSTRAINT `fk_article_category`
    FOREIGN KEY (`idcategory`)
    REFERENCES `dbsystem`.`category` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsystem`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsystem`.`person` (
  `idperson` INT NOT NULL AUTO_INCREMENT,
  `person_type` VARCHAR(20) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `document_type` VARCHAR(20) NULL,
  `document_number` VARCHAR(20) NULL,
  `address` VARCHAR(70) NULL,
  `phone` VARCHAR(20) NULL,
  `email` VARCHAR(50) NULL,
  PRIMARY KEY (`idperson`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsystem`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsystem`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `document_type` VARCHAR(20) NOT NULL,
  `document_number` VARCHAR(20) NOT NULL,
  `address` VARCHAR(70) NULL,
  `phone` VARCHAR(20) NULL,
  `email` VARCHAR(50) NULL,
  `position` VARCHAR(20) NULL,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(512) NOT NULL,
  `state` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsystem`.`purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsystem`.`purchase` (
  `idpurchase` INT NOT NULL AUTO_INCREMENT,
  `idsupplier` INT NOT NULL,
  `iduser` INT NOT NULL,
  `purchase_type` VARCHAR(20) NOT NULL,
  `purchase_series` VARCHAR(7) NULL,
  `purchase_number` VARCHAR(10) NOT NULL,
  `datetime` DATETIME NOT NULL,
  `tax` DECIMAL(4,2) NOT NULL,
  `total_purchase` DECIMAL(11,2) NOT NULL,
  `state` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idpurchase`),
  INDEX `fk_purchase_person_idx` (`idsupplier` ASC),
  INDEX `fk_purchase_user_idx` (`iduser` ASC),
  CONSTRAINT `fk_purchase_person`
    FOREIGN KEY (`idsupplier`)
    REFERENCES `dbsystem`.`person` (`idperson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_user`
    FOREIGN KEY (`iduser`)
    REFERENCES `dbsystem`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsystem`.`purchase_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsystem`.`purchase_detail` (
  `idpurchase_detail` INT NOT NULL AUTO_INCREMENT,
  `idpurchase` INT NOT NULL,
  `idarticle` INT NOT NULL,
  `quantity` INT NOT NULL,
  `purchase_price` DECIMAL(11,2) NOT NULL,
  `sale_price` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`idpurchase_detail`),
  INDEX `fk_detail_purchase_idx` (`idpurchase` ASC),
  INDEX `fk_detail_article_idx` (`idarticle` ASC),
  CONSTRAINT `fk_purchaseDetail_purchase`
    FOREIGN KEY (`idpurchase`)
    REFERENCES `dbsystem`.`purchase` (`idpurchase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchaseDetail_article`
    FOREIGN KEY (`idarticle`)
    REFERENCES `dbsystem`.`article` (`idarticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsystem`.`sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsystem`.`sale` (
  `idsale` INT NOT NULL AUTO_INCREMENT,
  `idclient` INT NOT NULL,
  `iduser` INT NOT NULL,
  `sale_type` VARCHAR(20) NOT NULL,
  `sale_series` VARCHAR(7) NULL,
  `sale_number` VARCHAR(10) NOT NULL,
  `datetime` DATETIME NOT NULL,
  `tax` DECIMAL(4,2) NOT NULL,
  `total_sale` DECIMAL(11,2) NOT NULL,
  `state` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idsale`),
  INDEX `fk_sale_person_idx` (`idclient` ASC),
  INDEX `fk_sale_user_idx` (`iduser` ASC),
  CONSTRAINT `fk_sale_person`
    FOREIGN KEY (`idclient`)
    REFERENCES `dbsystem`.`person` (`idperson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sale_user`
    FOREIGN KEY (`iduser`)
    REFERENCES `dbsystem`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsystem`.`sale_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsystem`.`sale_detail` (
  `idsale_detail` INT NOT NULL AUTO_INCREMENT,
  `idsale` INT NOT NULL,
  `idarticle` INT NOT NULL,
  `quantity` INT NOT NULL,
  `sale_price` DECIMAL(11,2) NOT NULL,
  `sale_discount` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`idsale_detail`),
  INDEX `fk_detail_sale_idx` (`idsale` ASC),
  INDEX `fk_detail_article_idx` (`idarticle` ASC),
  CONSTRAINT `fk_saleDetail_sale`
    FOREIGN KEY (`idsale`)
    REFERENCES `dbsystem`.`sale` (`idsale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_saleDetail_article`
    FOREIGN KEY (`idarticle`)
    REFERENCES `dbsystem`.`article` (`idarticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsystem`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsystem`.`permission` (
  `idpermission` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idpermission`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsystem`.`user_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsystem`.`user_permission` (
  `iduser_permission` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT NOT NULL,
  `idpermission` INT NOT NULL,
  PRIMARY KEY (`iduser_permission`),
  INDEX `fk_user_permission_idx` (`iduser` ASC),
  INDEX `fk_userperm_permission_idx` (`idpermission` ASC),
  CONSTRAINT `fk_userPerm_user`
    FOREIGN KEY (`iduser`)
    REFERENCES `dbsystem`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_userPerm_permission`
    FOREIGN KEY (`idpermission`)
    REFERENCES `dbsystem`.`permission` (`idpermission`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
